import type { Recipe } from '../types';

/**
 * Catalogue V1 — 22 recettes.
 *
 * Transcription de `files/RECETTES_REDIGEES.md` §2 : identifiants, quantités,
 * étapes, temps et portions y sont déjà arrêtés.
 *
 * **Ni les allergènes, ni les régimes compatibles, ni la nutrition ne figurent
 * ici.** Tous trois se déduisent des ingrédients (`diet.ts`, `nutrition.ts`) :
 * une liste recopiée à la main s’oublie au premier ajout de recette, et c’est
 * précisément ce qui est arrivé dans le document source, où les régimes
 * déclarés sont tantôt complets, tantôt abrégés, tantôt écrits en français.
 *
 * Les quantités valent pour la recette **entière** ; `servings` dit combien de
 * portions elle produit.
 */
export const RECIPES: readonly Recipe[] = [
  // --- Petits-déjeuners ----------------------------------------------------
  {
    id: 'skyr_berries_oats',
    name: 'Bol de skyr, fruits rouges & flocons',
    mealTypes: ['breakfast'],
    tags: ['high_protein', 'quick', 'sweet'],
    ingredients: [
      { refId: 'skyr', quantityG: 200 },
      { refId: 'mixed_berries', quantityG: 80 },
      { refId: 'rolled_oats', quantityG: 30 },
      { refId: 'honey', quantityG: 10 },
    ],
    steps: [
      'Verse le skyr dans un bol.',
      'Ajoute les fruits rouges et les flocons d’avoine.',
      'Termine par un filet de miel. C’est prêt.',
    ],
    prepTimeMin: 5,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'porridge_banana',
    name: 'Porridge protéiné banane-cannelle',
    mealTypes: ['breakfast'],
    tags: ['high_fiber', 'comfort'],
    ingredients: [
      { refId: 'rolled_oats', quantityG: 50 },
      { refId: 'milk_semi', quantityG: 200, display: '200 ml' },
      { refId: 'banana', quantityG: 100 },
      { refId: 'protein_powder_whey', quantityG: 20 },
    ],
    steps: [
      'Fais chauffer les flocons avec le lait à feu doux, en remuant, 5 min.',
      'Hors du feu, incorpore la protéine en poudre et une pincée de cannelle.',
      'Ajoute la banane en rondelles et sers chaud.',
    ],
    prepTimeMin: 10,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'avocado_egg_toast',
    name: 'Toast avocat & œuf poché',
    mealTypes: ['breakfast'],
    tags: ['savory', 'quick'],
    ingredients: [
      { refId: 'bread_wholegrain', quantityG: 60 },
      { refId: 'avocado', quantityG: 60 },
      { refId: 'egg', quantityG: 55, display: '1 œuf' },
    ],
    steps: [
      'Fais griller le pain et pocher l’œuf 3 min dans une eau frémissante.',
      'Écrase l’avocat sur le pain, sale et poivre.',
      'Dépose l’œuf poché par-dessus.',
    ],
    prepTimeMin: 10,
    difficulty: 'medium',
    servings: 1,
  },
  {
    id: 'overnight_oats_vegan',
    name: 'Overnight oats vanille',
    mealTypes: ['breakfast'],
    tags: ['no_cook', 'batch_cook', 'high_fiber'],
    ingredients: [
      { refId: 'rolled_oats', quantityG: 50 },
      { refId: 'soy_milk', quantityG: 200, display: '200 ml' },
      { refId: 'chia_seeds', quantityG: 15 },
      { refId: 'mixed_berries', quantityG: 60 },
    ],
    steps: [
      'Mélange flocons, boisson soja et graines de chia dans un bocal.',
      'Laisse au frais toute la nuit.',
      'Au matin, ajoute les fruits rouges et déguste.',
    ],
    prepTimeMin: 5,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'veggie_cheese_omelette',
    name: 'Omelette légumes & fromage',
    mealTypes: ['breakfast', 'lunch'],
    tags: ['high_protein', 'one_pan'],
    ingredients: [
      { refId: 'egg', quantityG: 110, display: '2 œufs' },
      { refId: 'bell_pepper', quantityG: 60 },
      { refId: 'spinach', quantityG: 30 },
      { refId: 'cheese_emmental', quantityG: 20 },
      { refId: 'olive_oil', quantityG: 5 },
    ],
    steps: [
      'Fais revenir le poivron émincé et les épinards dans l’huile.',
      'Verse les œufs battus, laisse prendre à feu moyen.',
      'Ajoute le fromage, replie l’omelette et sers.',
    ],
    prepTimeMin: 10,
    difficulty: 'easy',
    servings: 1,
  },

  // --- Déjeuners -----------------------------------------------------------
  {
    id: 'chicken_quinoa_salad',
    name: 'Salade poulet grillé & quinoa',
    mealTypes: ['lunch'],
    tags: ['high_protein', 'fresh', 'batch_cook'],
    ingredients: [
      { refId: 'chicken_breast_raw', quantityG: 240 },
      { refId: 'quinoa_raw', quantityG: 100 },
      { refId: 'tomato', quantityG: 100 },
      { refId: 'cucumber', quantityG: 100 },
      { refId: 'olive_oil', quantityG: 15 },
    ],
    steps: [
      'Cuis le quinoa selon l’emballage, laisse tiédir.',
      'Grille le poulet à la poêle, coupe-le en lamelles.',
      'Mélange quinoa, légumes en dés, poulet et huile d’olive. Assaisonne.',
    ],
    prepTimeMin: 20,
    difficulty: 'easy',
    servings: 2,
  },
  {
    id: 'chickpea_buddha_bowl',
    name: 'Buddha bowl pois chiches rôtis',
    mealTypes: ['lunch'],
    tags: ['high_protein', 'high_fiber'],
    ingredients: [
      { refId: 'chickpeas_cooked', quantityG: 240 },
      { refId: 'quinoa_raw', quantityG: 80 },
      { refId: 'carrot', quantityG: 100 },
      { refId: 'spinach', quantityG: 60 },
      { refId: 'olive_oil', quantityG: 15 },
    ],
    steps: [
      'Rôtis les pois chiches au four 20 min avec un peu d’huile et des épices.',
      'Cuis le quinoa, râpe la carotte.',
      'Dresse le bol : quinoa, épinards, carotte, pois chiches. Arrose d’huile.',
    ],
    prepTimeMin: 25,
    difficulty: 'easy',
    servings: 2,
  },
  {
    id: 'tuna_wrap',
    name: 'Wrap thon & crudités',
    mealTypes: ['lunch'],
    tags: ['high_protein', 'quick'],
    ingredients: [
      { refId: 'whole_wheat_wrap', quantityG: 60 },
      { refId: 'canned_tuna', quantityG: 100 },
      { refId: 'tomato', quantityG: 60 },
      { refId: 'cucumber', quantityG: 60 },
      { refId: 'fromage_blanc_0', quantityG: 30 },
    ],
    steps: [
      'Tartine la galette de fromage blanc.',
      'Répartis le thon émietté et les crudités en dés.',
      'Roule serré, coupe en deux.',
    ],
    prepTimeMin: 10,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'red_lentil_dahl',
    name: 'Dahl de lentilles corail',
    mealTypes: ['lunch', 'dinner'],
    tags: ['high_protein', 'high_fiber', 'batch_cook', 'comfort'],
    ingredients: [
      { refId: 'lentils_raw', quantityG: 200 },
      { refId: 'coconut_milk', quantityG: 200, display: '200 ml' },
      { refId: 'onion', quantityG: 100 },
      { refId: 'tomato', quantityG: 150 },
      { refId: 'curry_spices', quantityG: 5 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Fais revenir l’oignon dans l’huile, ajoute les épices.',
      'Ajoute lentilles, tomates, lait de coco et 400 ml d’eau.',
      'Laisse mijoter 25 min jusqu’à ce que les lentilles soient fondantes.',
    ],
    prepTimeMin: 30,
    difficulty: 'easy',
    servings: 3,
  },

  // --- Dîners --------------------------------------------------------------
  {
    id: 'tofu_broccoli_stirfry',
    name: 'Poêlée tofu, brocoli & riz',
    mealTypes: ['dinner'],
    tags: ['high_protein', 'one_pan'],
    ingredients: [
      { refId: 'tofu_firm', quantityG: 250 },
      { refId: 'broccoli_raw', quantityG: 200 },
      { refId: 'white_rice_raw', quantityG: 120 },
      { refId: 'olive_oil', quantityG: 15 },
    ],
    steps: [
      'Cuis le riz. En parallèle, dore le tofu en cubes dans l’huile.',
      'Ajoute le brocoli, fais sauter 6-8 min.',
      'Sers le sauté sur le riz, assaisonne (sauce soja si tu veux).',
    ],
    prepTimeMin: 20,
    difficulty: 'medium',
    servings: 2,
  },
  {
    id: 'salmon_sweet_potato',
    name: 'Saumon, patate douce & épinards',
    mealTypes: ['dinner'],
    tags: ['high_protein'],
    ingredients: [
      { refId: 'salmon_raw', quantityG: 240 },
      { refId: 'sweet_potato_raw', quantityG: 300 },
      { refId: 'spinach', quantityG: 100 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Enfourne la patate douce en cubes 25 min à 200 °C.',
      'Cuis le saumon à la poêle, 4 min par face.',
      'Fais tomber les épinards à la poêle. Dresse le tout.',
    ],
    prepTimeMin: 30,
    difficulty: 'easy',
    servings: 2,
  },
  {
    id: 'chicken_basquaise',
    name: 'Poulet basquaise express',
    mealTypes: ['dinner'],
    tags: ['high_protein', 'one_pan'],
    ingredients: [
      { refId: 'chicken_breast_raw', quantityG: 240 },
      { refId: 'bell_pepper', quantityG: 150 },
      { refId: 'tomato', quantityG: 200 },
      { refId: 'onion', quantityG: 80 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Dore le poulet dans l’huile, réserve.',
      'Fais revenir oignon et poivrons, ajoute les tomates.',
      'Remets le poulet, mijote 15 min à couvert.',
    ],
    prepTimeMin: 25,
    difficulty: 'easy',
    servings: 2,
  },
  {
    id: 'chili_sin_carne',
    name: 'Chili sin carne',
    mealTypes: ['dinner'],
    tags: ['high_protein', 'high_fiber', 'batch_cook', 'spicy'],
    ingredients: [
      { refId: 'red_beans_cooked', quantityG: 360 },
      { refId: 'tomato', quantityG: 300 },
      { refId: 'bell_pepper', quantityG: 150 },
      { refId: 'onion', quantityG: 100 },
      { refId: 'curry_spices', quantityG: 5 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Fais revenir oignon et poivrons dans l’huile.',
      'Ajoute haricots, tomates et épices (cumin, paprika, piment).',
      'Laisse mijoter 20 min. Sers tel quel ou avec un peu de riz.',
    ],
    prepTimeMin: 30,
    difficulty: 'easy',
    servings: 3,
  },
  {
    id: 'veggie_chickpea_curry',
    name: 'Curry de légumes & pois chiches',
    mealTypes: ['dinner'],
    tags: ['high_fiber', 'comfort'],
    ingredients: [
      { refId: 'chickpeas_cooked', quantityG: 300 },
      { refId: 'mixed_vegetables', quantityG: 300 },
      { refId: 'coconut_milk', quantityG: 200, display: '200 ml' },
      { refId: 'onion', quantityG: 100 },
      { refId: 'curry_spices', quantityG: 8 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Fais revenir l’oignon et les épices dans l’huile.',
      'Ajoute légumes, pois chiches et lait de coco.',
      'Mijote 15 min. Sers chaud.',
    ],
    prepTimeMin: 25,
    difficulty: 'easy',
    servings: 3,
  },
  {
    id: 'cod_papillote',
    name: 'Cabillaud en papillote & légumes',
    mealTypes: ['dinner'],
    tags: ['low_calorie', 'high_protein'],
    ingredients: [
      { refId: 'cod_raw', quantityG: 240 },
      { refId: 'mixed_vegetables', quantityG: 300 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Dépose chaque dos de cabillaud sur du papier cuisson.',
      'Entoure de légumes, filet d’huile, sel, herbes.',
      'Ferme les papillotes, enfourne 18 min à 200 °C.',
    ],
    prepTimeMin: 25,
    difficulty: 'easy',
    servings: 2,
  },
  {
    id: 'beef_greenbeans_potato',
    name: 'Steak haché, haricots verts & pommes de terre',
    mealTypes: ['dinner'],
    tags: ['high_protein', 'comfort'],
    ingredients: [
      { refId: 'lean_beef_raw', quantityG: 240 },
      { refId: 'green_beans', quantityG: 250 },
      { refId: 'potato_raw', quantityG: 300 },
      { refId: 'olive_oil', quantityG: 10 },
    ],
    steps: [
      'Cuis les pommes de terre à l’eau ou à la vapeur.',
      'Poêle les haricots verts, puis les steaks selon ta cuisson.',
      'Sers l’assiette équilibrée, assaisonne.',
    ],
    prepTimeMin: 25,
    difficulty: 'easy',
    servings: 2,
  },

  // --- Collations ----------------------------------------------------------
  {
    id: 'fromage_blanc_honey_walnuts',
    name: 'Fromage blanc, miel & noix',
    mealTypes: ['snack'],
    tags: ['high_protein', 'no_cook', 'sweet'],
    ingredients: [
      { refId: 'fromage_blanc_0', quantityG: 150 },
      { refId: 'honey', quantityG: 10 },
      { refId: 'walnuts', quantityG: 15 },
    ],
    steps: ['Verse le fromage blanc dans un bol.', 'Ajoute le miel et les noix concassées.'],
    prepTimeMin: 3,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'hummus_veggie_sticks',
    name: 'Houmous & bâtonnets de légumes',
    mealTypes: ['snack'],
    tags: ['high_fiber', 'no_cook', 'savory'],
    ingredients: [
      { refId: 'hummus', quantityG: 80 },
      { refId: 'carrot', quantityG: 80 },
      { refId: 'cucumber', quantityG: 80 },
      { refId: 'bell_pepper', quantityG: 60 },
    ],
    steps: ['Coupe les légumes en bâtonnets.', 'Sers avec le houmous.'],
    prepTimeMin: 5,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'apple_peanut_butter',
    name: 'Pomme & beurre de cacahuète',
    mealTypes: ['snack'],
    tags: ['no_cook', 'quick'],
    ingredients: [
      { refId: 'apple', quantityG: 150 },
      { refId: 'peanut_butter', quantityG: 20 },
    ],
    steps: ['Coupe la pomme en quartiers.', 'Trempe dans le beurre de cacahuète.'],
    prepTimeMin: 3,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'green_protein_smoothie',
    name: 'Smoothie protéiné vert',
    mealTypes: ['snack', 'breakfast'],
    tags: ['high_protein', 'no_cook', 'fresh'],
    ingredients: [
      { refId: 'soy_milk', quantityG: 250, display: '250 ml' },
      { refId: 'banana', quantityG: 100 },
      { refId: 'spinach', quantityG: 30 },
      { refId: 'protein_powder_pea', quantityG: 25 },
    ],
    steps: ['Mets tous les ingrédients au blender.', 'Mixe jusqu’à consistance lisse. Sers frais.'],
    prepTimeMin: 5,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'boiled_eggs_veggies',
    name: 'Œufs durs & crudités',
    mealTypes: ['snack'],
    tags: ['high_protein', 'no_cook'],
    ingredients: [
      { refId: 'egg', quantityG: 110, display: '2 œufs' },
      { refId: 'cucumber', quantityG: 80 },
      { refId: 'tomato', quantityG: 80 },
    ],
    steps: [
      'Cuis les œufs 9 min dans l’eau bouillante, refroidis-les.',
      'Écale et sers avec les crudités.',
    ],
    prepTimeMin: 12,
    difficulty: 'easy',
    servings: 1,
  },
  {
    id: 'greek_yogurt_granola',
    name: 'Yaourt grec, granola & fruits',
    mealTypes: ['snack', 'breakfast'],
    tags: ['high_protein', 'sweet', 'quick'],
    ingredients: [
      { refId: 'greek_yogurt_0', quantityG: 170 },
      { refId: 'granola', quantityG: 40 },
      { refId: 'mixed_berries', quantityG: 60 },
    ],
    steps: ['Verse le yaourt dans un bol.', 'Ajoute le granola et les fruits rouges.'],
    prepTimeMin: 3,
    difficulty: 'easy',
    servings: 1,
  },
];
